### ISSUE TITLE
Failing to parse string literals 

### ISSUE THREAD

**Issue by AaronNGray** [AaronNGray/rdf-tools#1]
Error: Expected arguments[0] iri to look like an IRI for 'rdf-tools typescript activitystreams-owl.ttl'

```
C:\Users\aaron\GitHub\AaronNGray\rdf-tools>rdf-tools typescript activitystreams-owl.ttl
index.js typescript [options] <pattern>

generate TypeScript from RDF

Options:
  -D, --debug            output debug information                                          [boolean]
  -h, --help             Show help                                                         [boolean]
  -p, --prefixes         output prefixes                                                   [boolean]
  -i, --iris             output iris                                                       [boolean]
  -c, --classes          output classes                                                    [boolean]
  -t, --type-guards      output type guards                                                [boolean]
  -d, --default-exports  output default exports                                            [boolean]
  -v, --version          Show version number                                               [boolean]

Error: Expected arguments[0] `iri` to look like an IRI
    at new NamedNode (C:\Users\aaron\AppData\Roaming\npm\node_modules\rdf-tools\node_modules\rdf\lib\RDFNode.js:353:51)
    at new Triple (C:\Users\aaron\AppData\Roaming\npm\node_modules\rdf-tools\node_modules\rdf\lib\RDFNode.js:106:29)
    at exports.RDFEnvironment.createTriple (C:\Users\aaron\AppData\Roaming\npm\node_modules\rdf-tools\node_modules\rdf\lib\RDFEnvironment.js:49:9)
    at C:\Users\aaron\AppData\Roaming\npm\node_modules\rdf-tools\dist\helpers\graph.js:9:35
    at Array.reduce (<anonymous>)
    at Object.getRDFGraph (C:\Users\aaron\AppData\Roaming\npm\node_modules\rdf-tools\dist\helpers\graph.js:7:20)
    at Object.<anonymous> (C:\Users\aaron\AppData\Roaming\npm\node_modules\rdf-tools\dist\model\classes.js:58:31)
    at Generator.next (<anonymous>)
    at C:\Users\aaron\AppData\Roaming\npm\node_modules\rdf-tools\dist\model\classes.js:7:71
    at new Promise (<anonymous>)
```

**Comment by AaronNGray** [comment]
https://github.com/awwright/node-rdf/blob/master/lib/RDFNode.js#L353 modified to :-
```
if(!iri.match(api.NamedNode.SCHEME_MATCH)) throw new Error(`Expected arguments[0] '${iri}' to look like an IRI`);
```
```
Error: Expected arguments[0] '"Extended Activity Streams 2.0 Vocabulary"@en' to look like an IRI
    at new NamedNode (C:\Users\aaron\GitHub\AaronNGray\rdf-tools\node_modules\rdf\lib\RDFNode.js:353:51)
```
https://github.com/ontola/ontologies/blob/master/ontologies/as/ontology.ttl#L11
```
<https://www.w3.org/ns/activitystreams#> a owl:Ontology ;
  rdfs:comment "Extended Activity Streams 2.0 Vocabulary"@en ;
  rdfs:label "Activity Streams 2.0"@en ;
  owl:imports <http://www.w3.org/ns/prov#> .
```
